AWSTemplateFormatVersion: '2010-09-09'
Description: cloudformation template to deploy resources to aws

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "aws-github-ci-cd-data"

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
